v1-post-create:
    path: /posts
    controller: App\Http\V1\Action\Post\Create\CreateAction
    methods: POST

v1-post-update:
    path: /posts/{id}
    controller: App\Http\V1\Action\Post\Update\UpdateAction
    methods: PUT

v1-post-delete:
    path: /posts/{id}
    controller: App\Http\V1\Action\Post\Delete\DeleteAction
    methods: DELETE

v1-post-read:
    path: /posts/{id}
    controller: App\Http\V1\Action\Post\Read\ReadAction
    methods: GET

v1-post-user:
    path: /user/{id}/posts
    controller: App\Http\V1\Action\Post\ByUser\ByUserAction
    methods: GET

