v1-todo-create:
    path: /todos
    controller: App\Http\V1\Action\Todo\Create\CreateAction
    methods: POST

v1-todo-update:
    path: /todos/{id}
    controller: App\Http\V1\Action\Todo\Update\UpdateAction
    methods: PUT

v1-todo-delete:
    path: /todos/{id}
    controller: App\Http\V1\Action\Todo\Delete\DeleteAction
    methods: DELETE

v1-todo-read:
    path: /todos/{id}
    controller: App\Http\V1\Action\Todo\Read\ReadAction
    methods: GET

v1-todo-user:
    path: /user/{id}/todos
    controller: App\Http\V1\Action\Todo\ByUser\ByUserAction
    methods: GET

